#!/bin/bash

show_users() {
    getent passwd | cut - d: -f1,6 | sort
}

show_processes() {
    ps - eo pid, cmd --sort = pid
}

show_help() {
        echo "Usage: $0 [OPTIONS]"
        echo "Options:"
        echo "  -u, --users                   Show list of users and their home directories"
        echo "  -p, --processes               Show list of running processes"
        echo "  -h, --help                    Show help message"
        echo "  -l PATH, --log PATH           Redirect output to a file at the specified PATH"
        echo "  -e PATH, --errors PATH        Redirect error output to a file at the specified PATH"
}

redirect_log() {
    if [[ -f $1 ]] || [[ -d $1 ]]; then
        exec > $1
    else
        echo "Error: Invalid path specified" >&2
        exit 1
    fi
}

redirect_errors() {
    if [[ -f $1 ]] || [[ -d $1 ]]; then
        exec 2 > $1
    else
        echo "Error: Invalid path specified" >&2
        exit 1
    fi
}

if [ $# -eq 0 ]; then
	echo "Error: No arguments. Use -h --help." >&2
	exit 1
fi

while getopts "u:p:h:l:e:-:" opt; do
    case $opt in
        u)
            show_users
            ;;
        p)
            show_processes
            ;;
        h)
            show_help
            ;;
        l)
            redirect_log $OPTARG
            ;;
        e)
            redirect_errors $OPTARG
            ;;
        -)
            case $OPTARG in
                users)
                    show_users
                    ;;
                processes)
                    show_processes
                    ;;
                help)
                    show_help
                    ;;
                log)
                    redirect_log $2
                    ;;
                errors)
                    redirect_errors $2
                    ;;
                *)
                    echo "Error: Invalid option" >&2
                    exit 1
                    ;;
                esac;;
        \? )
              show_help
              ;;
    esac
done

